{{- $sharderCount := .Values.sharder.sharderCount | int }}
{{- $sharderCount := add $sharderCount 1 | int }}
{{- range $i := untilStep 1 $sharderCount 1 }}

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cassandra-0{{ $i }}
    tier: prod
  name: cassandra-0{{ $i }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cassandra-0{{ $i }}
      tier: prod
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: cassandra-0{{ $i }}
        tier: prod
    spec:
      containers:
        - image: cassandra:3.11.4
          name: cassandra-0{{ $i }}
          resources:
            limits:
              cpu: 500m
              memory: 1.5Gi
            requests:
              cpu: 50m
              memory: 500Mi
          env:
            - name: MAX_HEAP_SIZE
              value: 512M
            - name: HEAP_NEWSIZE
              value: 100M
          volumeMounts:
            - mountPath: /var/lib/cassandra/data
              name: sharder-data-pvc-0{{ $i }}
              subPath: cassandra
      imagePullSecrets:
        - name: regcred
      restartPolicy: Always
      volumes:
        - name: sharder-data-pvc-0{{ $i }}
          persistentVolumeClaim:
            claimName: sharder-data-pvc-0{{ $i }}


{{- end }}