{{- $sharderCount := .Values.sharder.sharderCount | int }}
{{- $sharderCount := add $sharderCount 1 | int }}
{{- range $i := untilStep 1 $sharderCount 1 }}

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: sharder-0{{ $i }}
    tier: prod
  name: sharder-0{{ $i }}
spec:
  replicas: {{ $.Values.sharder.replicaCount }}
  selector:
    matchLabels:
      app: sharder-0{{ $i }}
      tier: prod
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: sharder-0{{ $i }}
        tier: prod
    spec:
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - cassandra-0{{ $i }}
              topologyKey: "kubernetes.io/hostname"
      containers:
        - name: sharder-0{{ $i }}
          image: {{ $.Values.sharder.image.repository }}:{{ $.Values.sharder.image.tag }}
          imagePullPolicy: {{ $.Values.sharder.image.pullPolicy }}
          ports:
            - containerPort: 3120{{ $i }}
          resources:
            limits:
              cpu: 1500m
              memory: 1500Mi
            requests:
              cpu: 500m
              memory: 750Mi
          command:
            - /bin/sh
            - -c
            - mkdir -p /0chain/data/blocks && mkdir -p /0chain/data/rocksdb && ./bin/sharder --deployment_mode 0 --keys_file config/b0snode0{{ $i }}_keys.txt --minio_file config/minio_config.txt
          env:
            - name: CASSANDRA_CLUSTER
              value: cassandra-0{{ $i }}
            - name: DOCKER
              value: "true"
          volumeMounts:
            - mountPath: /0chain/config/b0snode0{{ $i }}_keys.txt
              name: sm-config-pvc
              subPath: b0snode0{{ $i }}_keys.txt
            - mountPath: /0chain/config/magicBlock.json
              name: magicblock-pvc
              subPath: magicBlock.json
            - mountPath: /0chain/config/initial-state.yaml
              name: initial-state-pvc
              subPath: initial-state.yaml
            - mountPath: /0chain/config/nodes.yaml
              name: nodes-yaml-pvc
              subPath: nodes.yaml
            - mountPath: /0chain/config/n2n_delay.yaml
              name: n2n-delay-yaml
              subPath: n2n_delay.yaml
            - mountPath: /0chain/config/sc.yaml
              name: sc-config
              subPath: sc.yaml
            - mountPath: /0chain/config/minio_config.txt
              name: minio-config-sharder
              subPath: minio_config.txt
            - mountPath: /0chain/config/b0owner_keys.txt
              name: owner-config
              subPath: b0owner_keys.txt
            - mountPath: /0chain/config/0chain.yaml
              name: zchain-yaml-config
              subPath: 0chain.yaml
            - mountPath: /0chain/config/cassandra
              name: sharder-cassandra-config
            - mountPath: /0chain/log
              name: sharder-log-pvc-0{{ $i }}
            - mountPath: /0chain/data
              name: sharder-data-pvc-0{{ $i }}
        - name: filebeat-sidecar
          image: docker.elastic.co/beats/filebeat:7.8.0
          resources:
            limits:
              cpu: 100m
              memory: 100Mi
            requests:
              cpu: 50m
              memory: 50Mi 
          volumeMounts:
          - name: sharder-log-pvc-0{{ $i }}
            mountPath: /0chain/log
          - name: filebeat-config
            mountPath: /usr/share/filebeat/filebeat.yml
            subPath: filebeat.yml
      imagePullSecrets:
        - name: regcred
      restartPolicy: Always
      volumes:
        - name: n2n-delay-yaml
          configMap:
            name: n2n-delay-yaml
            defaultMode: 0755
        - name: sc-config
          configMap:
            name: sc-config
            defaultMode: 0755
        - name: minio-config-sharder
          secret:
            secretName: minio-config-sharder
            defaultMode: 0755
        - name: owner-config
          configMap:
            name: owner-config
            defaultMode: 0755
        - name: zchain-yaml-config
          configMap:
            name: zchain-yaml-config
            defaultMode: 0755
        - name: sharder-cassandra-config
          configMap:
            name: sharder-cassandra-config
            defaultMode: 0755
        - name: sharder-log-pvc-0{{ $i }}
          persistentVolumeClaim:
            claimName: sharder-log-pvc-0{{ $i }}
        - name: sharder-data-pvc-0{{ $i }}
          persistentVolumeClaim:
            claimName: sharder-data-pvc-0{{ $i }}
        - name: sm-config-pvc
          configMap:
            name: b0snode0{{ $i }}-keys
            defaultMode: 0755
        - name: nodes-yaml-pvc
          configMap:
            name: nodes
            defaultMode: 0755
        - name: magicblock-pvc
          configMap:
            name: magicblock
            defaultMode: 0755
        - name: initial-state-pvc
          configMap:
            name: initial-state
            defaultMode: 0755
        - name: sharder-sql-volume
          configMap:
            name: sharder-sql
            items:
              - key: truncate_tables.sql
                path: truncate_tables.sql
              - key: txn_summary.sql
                path: txn_summary.sql
              - key: zerochain_keyspace.sql
                path: zerochain_keyspace.sql
        - name: sharder-bin-volume
          configMap:
            name: sharder-bin
            items:
              - key: cassandra-init.sh
                path: cassandra-init.sh
              - key: scylla-init.sh
                path: scylla-init.sh
              - key: wait-for-service.sh
                path: wait-for-service.sh
            defaultMode: 0755
        - name: filebeat-config
          configMap:
            name: filebeat-config
            defaultMode: 0755

{{- end }}