{{- $minerCount := .Values.miner.minerCount | int }}
{{- $minerCount := add $minerCount 1 | int }}
{{- range $i := untilStep 1 $minerCount 1 }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: miner-log-pvc-0{{ $i }}
  labels:
    {{- include "0helm-0chain.labels" $ | nindent 4 }}-miner-log-pvc-0{{ $i }}
spec:
  accessModes:
  - {{ $.Values.miner.persistence.accessMode_log_pvc }}
  resources:
    requests:
      storage: {{ $.Values.miner.persistence.size_log_pvc }}
  storageClassName: {{ $.Values.miner.persistence.storageClass_log_pvc }}{{ $i }}

{{- end }}