{{- $minerCount := .Values.miner.minerCount | int }}
{{- $minerCount := add $minerCount 1 | int }}
{{- range $i := untilStep 1 $minerCount 1 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    {{- include "0helm.labels" $ | nindent 6 }}-promtail-miner-0{{ $i }}
  name: promtail-miner-0{{ $i }}
data:
  promtail.yaml: |
    scrape_configs:
      - job_name: system
        static_configs:
          - targets:
              - localhost
            labels:
              job: promtail
              tag: miner-0{{ $i }}
              __path__: /0chain/log/0chain.log #collect log path
              
{{- end }}
