{{- $sharderCount := .Values.sharder.sharderCount | int }}
{{- $sharderCount := add $sharderCount 1 | int }}
{{- range $i := untilStep 1 $sharderCount 1 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    {{- include "0helm.labels" $ | nindent 6 }}-promtail-sharder-0{{ $i }}
  name: promtail-sharder-0{{ $i }}
data:
  promtail.yaml: |
    scrape_configs:
      - job_name: system
        static_configs:
          - targets:
              - localhost
            labels:
              job: promtail
              tag: sharder-0{{ $i }}
              __path__: /0chain/log/0chain.log #collect log path

{{- end }}
