apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    {{- include "0helm-0chain.labels" $ | nindent 6 }}-sharder-sql
  creationTimestamp: null
  name: sharder-sql
data:
  truncate_tables.sql: |
    truncate zerochain.txn_summary;
  txn_summary.sql: |
    CREATE TABLE IF NOT EXISTS zerochain.txn_summary (
    hash text PRIMARY KEY,
    round bigint
    );
    CREATE MATERIALIZED VIEW IF NOT EXISTS ZEROCHAIN.ROUND_TO_HASH
        AS SELECT ROUND, HASH FROM zerochain.txn_summary
        WHERE ROUND IS NOT NULL PRIMARY KEY (ROUND, HASH);
  zerochain_keyspace.sql: |
    CREATE  KEYSPACE IF NOT EXISTS zerochain
    WITH REPLICATION = { 'class' : 'SimpleStrategy', 'replication_factor' : 1 }
    AND DURABLE_WRITES = true;
  magic_block_map.sql: |
    CREATE TABLE IF NOT EXISTS zerochain.magic_block_map (
      id bigint,
      hash text,
      block_round bigint,
      PRIMARY KEY (id)
    );  
