{{- $minerCount := .Values.miner.minerCount | int }}
{{- $minerCount := add $minerCount 1 | int }}
{{- range $i := untilStep 1 $minerCount 1 }}

apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  labels:
    app: redis-0{{ $i }}
    tier: prod
  name: redis-0{{ $i }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-0{{ $i }}
      tier: prod
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: redis-0{{ $i }}
        tier: prod
    spec:
      containers:
        - image: redis:alpine
          name: redis-0{{ $i }}
          resources:
            limits:
              cpu: 100m
              memory: 100Mi
            requests:
              cpu: 50m
              memory: 50Mi 
          args:
            - redis-server
            - /0chain/config/redis/state.redis.conf
          volumeMounts:
            - mountPath: /0chain/config/b0mnode0{{ $i }}_keys.txt
              name: sm-config-pvc
              subPath: b0mnode0{{ $i }}_keys.txt
            - mountPath: /0chain/config/nodes.yaml
              name: nodes-yaml-pvc
              subPath: nodes.yaml
            - mountPath: /0chain/config/sc.yaml
              name: sc-config
              subPath: sc.yaml
            - mountPath: /0chain/config/b0owner_keys.txt
              name: owner-config
              subPath: b0owner_keys.txt
            - mountPath: /0chain/config/0chain.yaml
              name: zchain-yaml-config
              subPath: 0chain.yaml
            - mountPath: /0chain/config/redis
              name: miner-redis-config
            - mountPath: /0chain/data
              name: miner-data-pvc-0{{ $i }}
      restartPolicy: Always
      volumes:
        - name: sm-config-pvc
          configMap:
            name: b0mnode0{{ $i }}-keys
            defaultMode: 0755
        - name: nodes-yaml-pvc
          configMap:
            name: nodes
            defaultMode: 0755
        - name: sc-config
          configMap:
            name: sc-config
            defaultMode: 0755
        - name: owner-config
          configMap:
            name: owner-config
            defaultMode: 0755
        - name: zchain-yaml-config
          configMap:
            name: zchain-yaml-config
            defaultMode: 0755
        - name: miner-redis-config
          configMap:
            name: miner-redis-config
            defaultMode: 0755
        - name: miner-data-pvc-0{{ $i }}
          persistentVolumeClaim:
            claimName: miner-data-pvc-0{{ $i }}

{{- end }}