{{- $minerCount := .Values.miner.minerCount | int }}
{{- $minerCount := add $minerCount 1 | int }}
{{- range $i := untilStep 1 $minerCount 1 }}

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: miner-0{{ $i }}
    tier: prod
  name: miner-0{{ $i }}
spec:
  replicas: {{ $.Values.miner.replicaCount }}
  selector:
    matchLabels:
      app: miner-0{{ $i }}
      tier: prod
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: miner-0{{ $i }}
        tier: prod
    spec:
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - redis-0{{ $i }}
              topologyKey: "kubernetes.io/hostname"
      containers:
        - image: {{ $.Values.miner.image.repository }}:{{ $.Values.miner.image.tag }}
          imagePullPolicy: {{ $.Values.miner.image.pullPolicy }}
          name: miner-0{{ $i }}
          ports:
            - containerPort: 3110{{ $i }}
          command:
            - /bin/sh
            - -c
            - mkdir -p /0chain/data/rocksdb && mkdir -p /0chain/data/redis/state && mkdir -p /0chain/data/redis/transactions &&  chmod -R 777 /0chain/data/redis && ./bin/miner --deployment_mode 0 --keys_file config/b0mnode0{{ $i }}_keys.txt --dkg_file config/b0mnode0{{ $i }}_dkg.json --delay_file config/n2n_delay.yaml
          env:
            - name: DOCKER
              value: "true"
            - name: REDIS_HOST
              value: redis-0{{ $i }}
            - name: REDIS_TXNS
              value: redis-txns-0{{ $i }}
          resources:
            limits:
              cpu: 1250m
              memory: 1000Mi
            requests:
              cpu: 500m
              memory: 500Mi
          volumeMounts:
            - mountPath: /0chain/config/b0mnode0{{ $i }}_keys.txt
              name: sm-config-pvc
              subPath: b0mnode0{{ $i }}_keys.txt
            - mountPath: /0chain/config/b0mnode0{{ $i }}_dkg.json
              name: dkg-config-pvc
              subPath: b0mnode0{{ $i }}_dkg.json
            - mountPath: /0chain/config/nodes.yaml
              name: nodes-yaml-pvc
              subPath: nodes.yaml
            - mountPath: /0chain/config/magicBlock.json
              name: magicblock-pvc
              subPath: magicBlock.json
            - mountPath: /0chain/config/initial-state.yaml
              name: initial-state-pvc
              subPath: initial-state.yaml
            - mountPath: /0chain/config/n2n_delay.yaml
              name: n2n-delay-yaml
              subPath: n2n_delay.yaml
            - mountPath: /0chain/config/sc.yaml
              name: sc-config
              subPath: sc.yaml
            - mountPath: /0chain/config/b0owner_keys.txt
              name: owner-config
              subPath: b0owner_keys.txt
            - mountPath: /0chain/config/0chain.yaml
              name: zchain-yaml-config
              subPath: 0chain.yaml
            - mountPath: /0chain/config/redis
              name: miner-redis-config
            - mountPath: /0chain/data
              name: miner-data-pvc-0{{ $i }}
            - mountPath: /0chain/log
              name: miner-log-pvc-0{{ $i }}
        - name: filebeat-sidecar
          image: docker.elastic.co/beats/filebeat:7.8.0
          resources:
            limits:
              cpu: 100m
              memory: 100Mi
            requests:
              cpu: 50m
              memory: 50Mi 
          volumeMounts:
          - name: miner-log-pvc-0{{ $i }}
            mountPath: /0chain/log
          - name: filebeat-config
            mountPath: /usr/share/filebeat/filebeat.yml
            subPath: filebeat.yml
      imagePullSecrets:
        - name: regcred
      restartPolicy: Always
      volumes:
        - name: n2n-delay-yaml
          configMap:
            name: n2n-delay-yaml
            defaultMode: 0755
        - name: sc-config
          configMap:
            name: sc-config
            defaultMode: 0755
        - name: owner-config
          configMap:
            name: owner-config
            defaultMode: 0755
        - name: zchain-yaml-config
          configMap:
            name: zchain-yaml-config
            defaultMode: 0755
        - name: miner-redis-config
          configMap:
            name: miner-redis-config
            defaultMode: 0755
        - name: miner-data-pvc-0{{ $i }}
          persistentVolumeClaim:
            claimName: miner-data-pvc-0{{ $i }}
        - name: miner-log-pvc-0{{ $i }}
          persistentVolumeClaim:
            claimName: miner-log-pvc-0{{ $i }}
        - name: sm-config-pvc
          configMap:
            name: b0mnode0{{ $i }}-keys
            defaultMode: 0755
        - name: dkg-config-pvc
          configMap:
            name: b0mnode0{{ $i }}-dkg 
            defaultMode: 0755
        - name: nodes-yaml-pvc
          configMap:
            name: nodes
            defaultMode: 0755
        - name: magicblock-pvc
          configMap:
            name: magicblock
            defaultMode: 0755
        - name: initial-state-pvc
          configMap:
            name: initial-state
            defaultMode: 0755
        - name: filebeat-config
          configMap:
            name: filebeat-config
            defaultMode: 0755

{{- end }}