{{- $sharderCount := .Values.blobber.sharderCount | int }}
{{- $sharderCount := add $sharderCount 1 | int }}
{{- range $i := untilStep 1 $sharderCount 1 }}

apiVersion: v1
kind: PersistentVolume
metadata:
  name: sharder-log-pv-0{{ $i }}
  labels:
    tier: prod
spec:
  storageClassName: {{ $.Values.sharder.persistence.storageClass_log_pv }}{{ $i }}
  capacity:
    storage: {{ $.Values.sharder.persistence.size_log_pv }}
  accessModes:
    - {{ $.Values.sharder.persistence.accessMode_log_pv }}
  hostPath:
    path: "/mnt/kubernetes/sharder-log-0{{ $i }}"

{{- end }}