{{- $sharderCount := .Values.sharder.sharderCount | int }}
{{- $sharderCount := add $sharderCount 1 | int }}
{{- range $i := untilStep 1 $sharderCount 1 }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sharder-data-pv-0{{ $i }}
  labels:
    {{- include "0helm-0chain.labels" $ | nindent 4 }}-sharder-data-pv-0{{ $i }}
spec:
  storageClassName: {{ $.Values.sharder.persistence.storageClass_data_pv }}{{ $i }}
  # claimRef:
  #   name: sm-config-pvc
  capacity:
    storage: {{ $.Values.sharder.persistence.size_data_pv }}
  accessModes:
    - {{ $.Values.sharder.persistence.accessMode_data_pv }}
  hostPath:
    path: "{{ $.Values.sharder.persistence.pvHostPath }}{{ $.Values.sharder.persistence.storageClass_data_pv }}{{ $i }}"

{{- end }}