name: CICD-01

on:
  workflow_dispatch:
    inputs:
      image:
        description: 'image tag'
        required: true
        default: latest

jobs:
  deploy:
    runs-on: ubuntu-20.04
    continue-on-error: true
    steps:
      - uses: actions/checkout@v2
      - uses: azure/setup-helm@v1
        with:
          version: 'v3.2.2'
      - name: Setup helm repo
        run: |
          helm repo add 0chain-helm http://0chain-helm-chart.s3-website.us-east-2.amazonaws.com/helmCharts/
          helm repo update
      - name: Setup kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.CICD01KC }}" | base64 -d > ~/.kube/config

      - name: Cleanup
        run: |
          helm list --short -n helmtest | xargs -L1 helm delete -n helmtest
          # cleanup directories here

      - name: Setup chain
        if: always()
        run: |
          helm upgrade --install --wait --timeout 120s 0chain -n helmtest --set sharder.sharderImage.tag=${{ github.event.inputs.image }} --set miner.minerImage.tag=${{ github.event.inputs.image }} 0chain-helm/zchain
     
          helm upgrade --install --wait --timeout 120s 0dns -n helmtest --set zdns.image.tag=${{ github.event.inputs.image }} --set zdns.host=devnet-0chain.net 0chain-helm/zdns

          helm upgrade --install --wait --timeout 120s blobber -n helmtest --set blobber.blobberImage.tag=${{ github.event.inputs.image }} --set validator.validatorImage.tag=${{ github.event.inputs.image }} 0chain-helm/blobber

          helm upgrade --install --wait --timeout 120s 0block -n helmtest --set block.blockImage.tag=${{ github.event.inputs.image }} --set block.host=devnet-0chain.net 0chain-helm/zblock

          helm upgrade --install --wait --timeout 120s explorer -n helmtest --set explorer.explorerImage.tag=${{ github.event.inputs.image }} --set explorer.host=devnet-0chain.net 0chain-helm/blockExplorer

          helm upgrade --install --wait --timeout 120s 0proxy -n helmtest --set proxy.image.tag=${{ github.event.inputs.image }} --set proxy.host=devnet-0chain.net 0chain-helm/zproxy

          helm upgrade --install --wait --timeout 120s 0box -n helmtest --set zbox.zboxImage.tag=${{ github.event.inputs.image }} --set zbox.host=devnet-0chain.net 0chain-helm/zbox

          helm upgrade --install --wait --timeout 120s 0search -n helmtest --set blockRecorder.blockRecorderImage.tag=${{ github.event.inputs.image }} --set blockRecorder.host=devnet-0chain.net 0chain-helm/zsearch

          helm upgrade --install --wait --timeout 120s blobber-stake -n helmtest --set blobberStack.blobberCount=6 --set blobberStack.host=devnet-0chain.net --set blobberStack.image.tag=latest 0chain-helm/blobberStake

          rm -rf ~/.kube